version: "3.0"
services:
  mclimate-vicki-encoder:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "McClimate Vicki Encoder"
      MODULE_TYPE: "Processing"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      EXECUTE_SINGLE_COMMAND: 'no'
      SINGLE_COMMAND: ''
    ports:
      - 80:80